name: cypress end to end

on:
  # push :
  # schedule:
  #   - cron: '30 15 * * 1-5'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run 🧪
        uses: cypress-io/github-action@v6
        with: 
          browser: chrome
          env: true
          spec: cypress/e2e/erp-in-out/checkout.cy.js
        env: 
           CYPRESS_USERNAME: ${{ secrets.CYPRESS_ERP_LOGIN }}
           CYPRESS_PASSWORD: ${{ secrets.CYPRESS_ERP_PASSWORD }}
